--Cədvəl :
--İşçi - (SAA, VəzifəId,Maaş)
--Vəzifə - (Ad)
--Filial - (Ad)
--Məhsul - (Ad, Alış qiyməti, Satış qiyməti)
--Satış - (MəhsulId, İşçiId,Filialİd, Satış tarixi)
--Sorğular : 
--1) Satış cədvəlində işçilərin , satılan məhsulların,
-- satışın olduğu filialın, məhsulun alış və satış qiyməti yazılsın.
--2) Bütün satışların cəmini tap.
--3) Cari ayda məhsul satışından gələn yekun məbləği tap
--4) Hər işçinin satdığı məhsul sayını tap
--5) Bu gün üzrə ən çox məhsul satılan filialı tap.
--6) Cari ayda ən çox satılan məhsulu tap.

--Insert kodlarını da saxlayın atanda onlar da gəlsin.
--Hər birinizə uğurlar
CREATE DATABASE COMPANY 
USE COMPANY
CREATE TABLE VEZIFE(
ID  INT  PRIMARY KEY IDENTITY,
VEZIFE NVARCHAR (50)
)
INSERT INTO VEZIFE
VALUES('SELLER1')
INSERT INTO VEZIFE
VALUES('SELLER2')
INSERT INTO VEZIFE
VALUES('SELLER3')


CREATE TABLE ISHCHILER(
ID  INT  PRIMARY KEY IDENTITY,
SAAD NVARCHAR (255),                  
VEZIFEID INT FOREIGN KEY REFERENCES VEZIFE(ID),
SALARY MONEY
)
INSERT INTO ISHCHILER
VALUES('CHRIS SMITH MARK',2,500)
INSERT INTO ISHCHILER
VALUES('TOM WILLIAMS LEO',1,650)
INSERT INTO ISHCHILER
VALUES('WILLIAM WILLIAMS TOMAS',3,800)


CREATE TABLE FILIAL(
ID  INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR (50)
)
INSERT INTO FILIAL
VALUES('BAKU')
INSERT INTO FILIAL
VALUES('SUMQAYIT')

CREATE TABLE PRODUCT(
ID  INT PRIMARY KEY IDENTITY,
NAME NVARCHAR (50),
ALISHQIYMET MONEY,
SATISHQIYMET MONEY
)
INSERT INTO PRODUCT
VALUES('BOOK',5.5,8)
INSERT INTO PRODUCT
VALUES('PEN',2.6,4.3)
INSERT INTO PRODUCT
VALUES('CASE',8.2,12)
INSERT INTO PRODUCT
VALUES('PENCIL',3.1,4.2)

CREATE TABLE SALE(
ID  INT PRIMARY KEY IDENTITY,
PRODUCTID INT REFERENCES PRODUCT(ID),
ISHCHIID INT REFERENCES ISHCHILER(ID),
FILIALID INT REFERENCES FILIAL(ID),
TARIX DATE     
)

INSERT INTO SALE
VALUES(1,1,1,'2022-07-08')
INSERT INTO SALE
VALUES(2,2,2,'2022-07-10')
INSERT INTO SALE
VALUES(3,3,1,'2022-06-10')
INSERT INTO SALE
VALUES(2,3,1,'2022-07-08')
INSERT INTO SALE
VALUES(3,2,2,'2022-07-08')


--QUERY1
SELECT ISHCHILER.SAAD 'ISHCHILER',PRODUCT.NAME 'MEHSULLAR',PRODUCT.ALISHQIYMET 'ALISH',PRODUCT.SATISHQIYMET 'SATISH',FILIAL.FILIAL 'FILIAL'
FROM SALE
JOIN ISHCHILER
ON
ISHCHILER.ID=SALE.ISHCHIID
JOIN PRODUCT
ON
PRODUCT.ID=SALE.PRODUCTID
JOIN FILIAL
ON
FILIAL.ID=SALE.FILIALID

--QUERY2
SELECT SUM(SATISHQIYMET) AS 'SATISHCEM'
FROM PRODUCT
JOIN SALE
ON
PRODUCT.ID=SALE.PRODUCTID

--QUERY3
SELECT SUM(SATISHQIYMET) 'YEKUN SATISH 'FROM PRODUCT
JOIN SALE
ON
SALE.PRODUCTID=PRODUCT.ID
WHERE MONTH(TARIX)='07'

--QUERY4
SELECT ISHCHILER.SAAD,COUNT(*) AS 'ISHCHILERIN SATDIQLARI (SAY)'
FROM SALE
join ISHCHILER
ON
ISHCHILER.ID=ISHCHIID
GROUP BY
ISHCHILER.SAAD 

--QUERY5
SELECT TOP 1  COUNT(SALE.PRODUCTID)  'SATILAN MEHSUL SAYI',FILIAL.FILIAL 'FILIAL' FROM SALE
JOIN FILIAL
ON 
SALE.FILIALID=FILIAL.ID
JOIN PRODUCT
ON
PRODUCTID=PRODUCT.ID
WHERE DAY(SALE.TARIX)='08'   
GROUP BY
FILIAL.FILIAL
ORDER BY COUNT(SALE.PRODUCTID) DESC



--QUERY6
SELECT TOP 1 COUNT(SALE.PRODUCTID) 'SATILAN MEHSUL SAYI',PRODUCT.NAME 'MEHSUL' FROM SALE
JOIN PRODUCT
ON
PRODUCTID=PRODUCT.ID
WHERE MONTH(TARIX)='07'
GROUP BY
PRODUCT.NAME
ORDER BY COUNT(SALE.PRODUCTID) DESC


















